### ISSUE TITLE
i hava a question

### ISSUE THREAD

**Issue by Ruwestbrook** [YJoe/RaceCarsAndStuff#1]
I do not understand your options in oil and cracks, what they represent

**Comment by YJoe** [comment]
When the oil option is on, tracks will have a few randomly placed oil spills, these will make your car slip when driven over. Similarly, cracks are placed randomly on the track, this element wasn't finished while making the game, I had intended to add damage to the car when the player drives over cracks or crashes into walls. Right now, cracks are just a nice graphics change as it varies the track at least a bit!
